# Import Dependencies

In [1]:
import pandas as pd

In [2]:
#Open IMDB ratings
data_imdb = pd.read_csv("imdb_ratings.csv")

In [3]:
#Review variables
data_imdb.head(10)

,imdb_title_id,weighted_average_vote,total_votes,mean_vote,median_vote,votes_10,votes_9,votes_8,votes_7,votes_6,...,females_30age_avg_vote,females_30age_votes,females_45age_avg_vote,females_45age_votes,top1000_voters_rating,top1000_voters_votes,us_voters_rating,us_voters_votes,non_us_voters_rating,non_us_voters_votes
0,tt0000009,5.9,154,5.9,6.0,12,4,10,43,28,...,5.7,13.0,4.5,4.0,5.7,34.0,6.4,51.0,6.0,70.0
1,tt0000574,6.1,589,6.3,6.0,57,18,58,137,139,...,6.2,23.0,6.6,14.0,6.4,66.0,6.0,96.0,6.2,331.0
2,tt0001892,5.8,188,6.0,6.0,6,6,17,44,52,...,5.8,4.0,6.8,7.0,5.4,32.0,6.2,31.0,5.9,123.0
3,tt0002101,5.2,446,5.3,5.0,15,8,16,62,98,...,5.5,14.0,6.1,21.0,4.9,57.0,5.5,207.0,4.7,105.0
4,tt0002130,7.0,2237,6.9,7.0,210,225,436,641,344,...,7.3,82.0,7.4,77.0,6.9,139.0,7.0,488.0,7.0,1166.0
5,tt0002199,5.7,484,5.8,6.0,33,15,48,80,123,...,5.1,13.0,6.5,15.0,5.5,67.0,5.9,173.0,5.6,181.0
6,tt0002423,6.8,753,6.8,7.0,80,65,105,209,142,...,7.2,40.0,8.2,34.0,6.2,88.0,6.6,139.0,6.8,455.0
7,tt0002445,6.2,273,6.2,6.0,15,8,30,74,66,...,6.3,11.0,6.2,5.0,5.7,41.0,5.8,40.0,6.2,154.0
8,tt0002452,6.7,198,7.1,7.0,53,7,23,35,30,...,6.8,10.0,6.8,6.0,5.4,25.0,6.7,25.0,6.8,135.0
9,tt0002461,5.5,225,5.4,6.0,9,6,22,34,53,...,7.2,6.0,9.7,9.0,5.4,37.0,5.8,109.0,5.4,68.0

In [4]:
#Columns Names
columns = data_imdb.columns
print(columns)

Index(['imdb_title_id', 'weighted_average_vote', 'total_votes', 'mean_vote',
       'median_vote', 'votes_10', 'votes_9', 'votes_8', 'votes_7', 'votes_6',
       'votes_5', 'votes_4', 'votes_3', 'votes_2', 'votes_1',
       'allgenders_0age_avg_vote', 'allgenders_0age_votes',
       'allgenders_18age_avg_vote', 'allgenders_18age_votes',
       'allgenders_30age_avg_vote', 'allgenders_30age_votes',
       'allgenders_45age_avg_vote', 'allgenders_45age_votes',
       'males_allages_avg_vote', 'males_allages_votes', 'males_0age_avg_vote',
       'males_0age_votes', 'males_18age_avg_vote', 'males_18age_votes',
       'males_30age_avg_vote', 'males_30age_votes', 'males_45age_avg_vote',
       'males_45age_votes', 'females_allages_avg_vote',
       'females_allages_votes', 'females_0age_avg_vote', 'females_0age_votes',
       'females_18age_avg_vote', 'females_18age_votes',
       'females_30age_avg_vote', 'females_30age_votes',
       'females_45age_avg_vote', 'females_45age_votes',
       'top1000_voters_rating', 'top1000_voters_votes', 'us_voters_rating',
       'us_voters_votes', 'non_us_voters_rating', 'non_us_voters_votes'],
      dtype='object')

In [5]:
#Drop columns
to_drop = ['total_votes', 'mean_vote',
       'median_vote', 'votes_10', 'votes_9', 'votes_8', 'votes_7', 'votes_6',
       'votes_5', 'votes_4', 'votes_3', 'votes_2', 'votes_1',
       'allgenders_0age_avg_vote', 'allgenders_0age_votes',
       'allgenders_18age_avg_vote', 'allgenders_18age_votes',
       'allgenders_30age_avg_vote', 'allgenders_30age_votes',
       'allgenders_45age_avg_vote', 'allgenders_45age_votes',
       'males_allages_avg_vote', 'males_allages_votes', 'males_0age_avg_vote',
       'males_0age_votes', 'males_18age_avg_vote', 'males_18age_votes',
       'males_30age_avg_vote', 'males_30age_votes', 'males_45age_avg_vote',
       'males_45age_votes', 'females_allages_avg_vote',
       'females_allages_votes', 'females_0age_avg_vote', 'females_0age_votes',
       'females_18age_avg_vote', 'females_18age_votes',
       'females_30age_avg_vote', 'females_30age_votes',
       'females_45age_avg_vote', 'females_45age_votes',
       'top1000_voters_rating', 'top1000_voters_votes', 'us_voters_rating',
       'us_voters_votes', 'non_us_voters_rating', 'non_us_voters_votes']

In [6]:
#Setting Up
data_imdb.drop(to_drop, inplace=True, axis=1)

In [7]:
#Outcome after Drop
data_imdb.head(10)

  imdb_title_id  weighted_average_vote
0     tt0000009                    5.9
1     tt0000574                    6.1
2     tt0001892                    5.8
3     tt0002101                    5.2
4     tt0002130                    7.0
5     tt0002199                    5.7
6     tt0002423                    6.8
7     tt0002445                    6.2
8     tt0002452                    6.7
9     tt0002461                    5.5

In [8]:
imdb_rate = data_imdb.rename(columns ={'weighted_average_vote': 'avg_vote'})

In [9]:
imdb_rate.head()

  imdb_title_id  avg_vote
0     tt0000009       5.9
1     tt0000574       6.1
2     tt0001892       5.8
3     tt0002101       5.2
4     tt0002130       7.0

In [10]:
#Saving CSV
imdb_rate.to_csv('ratings.csv')